/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppNavigationDrawer: typeof import('./src/components/AppNavigationDrawer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Workspace: typeof import('./src/components/Workspace.vue')['default']
  }
}
