/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumbs: typeof import('./src/components/app/AppBreadcrumbs.vue')['default']
    AppDataDrawer: typeof import('./src/components/app/AppDataDrawer.vue')['default']
    AppHeader: typeof import('./src/components/app/AppHeader.vue')['default']
    AppMenu: typeof import('./src/components/app/AppMenu.vue')['default']
    AppNavigationDrawer: typeof import('./src/components/app/AppNavigationDrawer.vue')['default']
    AppSidebar: typeof import('./src/components/app/AppSidebar.vue')['default']
    BuilderContent: typeof import('./src/components/builder/BuilderContent.vue')['default']
    BuilderElementTab: typeof import('./src/components/BuilderElementTab.vue')['default']
    BuilderFieldList: typeof import('./src/components/BuilderFieldList.vue')['default']
    BuilderFieldsList: typeof import('./src/components/builder/BuilderFieldsList.vue')['default']
    BuilderFieldsTab: typeof import('./src/components/builder/BuilderFieldsTab.vue')['default']
    BuilderSearch: typeof import('./src/components/BuilderSearch.vue')['default']
    BuilderSearchElement: typeof import('./src/components/builder/BuilderSearchElement.vue')['default']
    copy: typeof import('./src/components/field/FieldText copy.vue')['default']
    FieldEmail: typeof import('./src/components/field/FieldEmail.vue')['default']
    FieldNumber: typeof import('./src/components/field/FieldNumber.vue')['default']
    FieldPassword: typeof import('./src/components/field/FieldPassword.vue')['default']
    FieldPhone: typeof import('./src/components/field/FieldPhone.vue')['default']
    FieldText: typeof import('./src/components/field/FieldText.vue')['default']
    FieldTextarea: typeof import('./src/components/field/FieldTextarea.vue')['default']
    FormHeading: typeof import('./src/components/static/FormHeading.vue')['default']
    Heading: typeof import('./src/components/static/Heading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaticButton: typeof import('./src/components/static/StaticButton.vue')['default']
    StructureContainer: typeof import('./src/components/structure/StructureContainer.vue')['default']
    Workspace: typeof import('./src/components/app/Workspace.vue')['default']
  }
}
